CC        = g++
PRJCFLAGS = -g -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS
LD        = g++
LDFLAGS   =
AR        = ar
ARFLAGS   =
RANLIB    = ranlib
RM        = rm
ECHO      = echo

SHELL     = /bin/sh

.SILENT :
