CC        = mpicxx
PRJCFLAGS = -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DSYSTEM=SYS_DEFAULT -DPTR_MEMDEBUG
LD        = g++
LDFLAGS   =
AR        = ar
ARFLAGS   =
RANLIB    = ranlib
RM        = rm
ECHO      = echo
RUN				= mpirun
TESTFILE	= /Users/jesseweaver/Desktop/_test_

SHELL     = /bin/sh

.SILENT :
